Repository romanlefler/SimpleWeather, pull requests merged in 2025-08, with the labels that each got.

#19 Add Bulgarian translation
  po/bg.po
Labels: translation

#26 transl(de): Update
  po/de.po
Labels: translation

#25 transl(tr): Update
  po/tr.po
Labels: translation

#24 Update it.po
  po/it.po
Labels: translation

#23 Fix cardinal points not being translated with gettext (fixes #22)
  src/units.ts
Labels: bug

#30 Add rule to Makefile that updates PO files with new strings
  Makefile
Labels: internal
